package com.org.cb.model;
// Generated 08-Jan-2018 22:50:01 by Hibernate Tools 5.1.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillingIndividual generated by hbm2java
 */
@Entity
@Table(name = "billing_individual", catalog = "devsample")
public class BillingIndividual implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer indBillId;
	private Integer indBillInvoiceNo;
	private String indBillerName;
	private String indReceiverName;
	private Date indBillDate;
	private Integer indBillQuantity;
	private BigDecimal indBillAmount;

	public BillingIndividual() {
	}

	public BillingIndividual(Integer indBillInvoiceNo, String indBillerName, String indReceiverName, Date indBillDate,
			Integer indBillQuantity, BigDecimal indBillAmount) {
		this.indBillInvoiceNo = indBillInvoiceNo;
		this.indBillerName = indBillerName;
		this.indReceiverName = indReceiverName;
		this.indBillDate = indBillDate;
		this.indBillQuantity = indBillQuantity;
		this.indBillAmount = indBillAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ind_BillID", unique = true, nullable = false)
	public Integer getIndBillId() {
		return this.indBillId;
	}

	public void setIndBillId(Integer indBillId) {
		this.indBillId = indBillId;
	}

	@Column(name = "Ind_BillInvoiceNo")
	public Integer getIndBillInvoiceNo() {
		return this.indBillInvoiceNo;
	}

	public void setIndBillInvoiceNo(Integer indBillInvoiceNo) {
		this.indBillInvoiceNo = indBillInvoiceNo;
	}

	@Column(name = "Ind_BillerName", length = 30)
	public String getIndBillerName() {
		return this.indBillerName;
	}

	public void setIndBillerName(String indBillerName) {
		this.indBillerName = indBillerName;
	}

	@Column(name = "Ind_ReceiverName", length = 30)
	public String getIndReceiverName() {
		return this.indReceiverName;
	}

	public void setIndReceiverName(String indReceiverName) {
		this.indReceiverName = indReceiverName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ind_BillDate", length = 10)
	public Date getIndBillDate() {
		return this.indBillDate;
	}

	public void setIndBillDate(Date indBillDate) {
		this.indBillDate = indBillDate;
	}

	@Column(name = "Ind_BillQuantity")
	public Integer getIndBillQuantity() {
		return this.indBillQuantity;
	}

	public void setIndBillQuantity(Integer indBillQuantity) {
		this.indBillQuantity = indBillQuantity;
	}

	@Column(name = "Ind_BillAmount", precision = 5, scale = 3)
	public BigDecimal getIndBillAmount() {
		return this.indBillAmount;
	}

	public void setIndBillAmount(BigDecimal indBillAmount) {
		this.indBillAmount = indBillAmount;
	}

}
